spring:
  datasource:
    # url: jdbc:h2:tcp://localhost/~/csf
    url: jdbc:h2:mem:csf
    driver-class-name: org.h2.Driver
    username: csf
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        hbm2ddl:
          auto: create
        format_sql: true
    show-sql: true
    generate-ddl: true

# H2 Settings (https://localhost:8080/h2-console
h2:
  console:
    enabled: true
    path: /h2-console